application: is-it-raining
version: 1
runtime: python27
api_version: 1
threadsafe: yes
automatic_scaling:
    min_idle_instances: 0
    max_idle_instances: 1  # default value
    min_pending_latency: 1s  # default value
    max_pending_latency: 5s
    max_concurrent_requests: 40

handlers:  
- url: /EST
  script: tweet_weather.app
  login: admin
  
- url: /CST
  script: tweet_weather.app
  login: admin
  
- url: /PST
  script: tweet_weather.app
  login: admin
  
- url: /GMT
  script: tweet_weather.app
  login: admin
  
- url: /UTC
  script: tweet_weather.app
  login: admin
  
- url: /UTCm3
  script: tweet_weather.app
  login: admin
  
- url: /UTC10
  script: tweet_weather.app
  login: admin
  
- url: /STATS
  script: tweet_weather.app
  login: admin

- url: .*
  script: main.app
  login: admin

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: ssl
  version: latest
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?.*\.py[co]

